### ISSUE TITLE
No mention of supported java client information to locate the flutter elements

### ISSUE THREAD

**Issue by suryak-cs** [AppiumTestDistribution/appium-flutter-integration-driver#15]
There is no mention of java clients to locate the flutter elements in the readme. Also can we add tests in java in `appium-flutter-integration-driver/tree/main/test`

Can I use flutter integration driver to run java based tests?

**Comment by saikrishna321** [comment]
@suryak-cs We are working on java APIs. Once completed will update the tests.

**Comment by suryak-cs** [comment]
Thank you @saikrishna321
