### ISSUE TITLE
Does Java Client support  feature mock image

### ISSUE THREAD

**Issue by vudiuht** [AppiumTestDistribution/appium-flutter-integration-driver#74]
@saikrishna321 could you help provide whether Java Client support the feature: Mock Image?

**Comment by saikrishna321** [comment]
@vudiuht Yes we will surely support mock in java. We are currently getting the finder added to the official java-client bindings. Once the PRs are merged. We will update the repo with details.

**Comment by saikrishna321** [comment]
Done. Please look at java-client v9.3.0
