### ISSUE TITLE
Swich context : Flutter and Native app 

### ISSUE THREAD

**Issue by thuonglai** [AppiumTestDistribution/appium-flutter-integration-driver#78]
Hi @saikrishna321 . When i change context from flutter to native app as the following code

```

WebElement inputPhoneNumber = androidDriver().findElement(FlutterBy.key(registrationPhoneField));
        waitForVisible(inputPhoneNumber);
        inputPhoneNumber.sendKeys(mobileNumber);

String otpXpath = "//*[@class='android.widget.EditText']";
        WebElement element = androidDriver().findElement(AppiumBy.xpath(otpXpath));
        element.clear();
      element.sendKeys(otp);
```

It happen error "org.openqa.selenium.InvalidArgumentException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 10 path $.text
" in line  element.sendKeys(otp);

Please guide me how to change context between flutter and native app. Thanks

**Comment by saikrishna321** [comment]
@thuonglai please share full server logs and also device logs as gist

**Comment by vudiuht** [comment]
hi @saikrishna321,  FlutterBy is for FLUTTER context and NATIVEAPP and WEBVIEW don't have example to know which context we are in?
When using Flutter Driver we should call:
 androidDriver().context("NATIVE_APP"); to switch to NATIVE_APP context.
 androidDriver().context("WEBVIEW"); to switch to WEBVIEW context
 androidDriver().context("FLUTTER"); to switch to FLUTTER context.
