### ISSUE TITLE
Not able to mock camera in java-client 

### ISSUE THREAD

**Issue by saikrishna321** [AppiumTestDistribution/appium-flutter-integration-driver#84]
https://github.com/appium/java-client/issues/2210

**Comment by saikrishna321** [comment]
@thuonglai

**Comment by thuonglai** [comment]
@saikrishna321 . As our dev team said, my project use MLKit of android vs avfoundation of ios

**Comment by saikrishna321** [comment]
@thuonglai Thanks for confirming. We only support mocking ImagePicker module 


Can you confirm if you are using https://pub.dev/packages/google_ml_kit ?

**Comment by thuonglai** [comment]
@saikrishna321  We use https://pub.dev/packages/fast_barcode_scanner
I see some code has ImagePicker in some screen but not in screen i want to scan QR code. And i start appium server with --allow-insecure=adb_shell

**Comment by saikrishna321** [comment]
@thuonglai we dont support this module. I don't we will add support the module u shared! It was last released 2yrs back and also says under development.

**Comment by diuvuaxlehire** [comment]
@saikrishna321 could you help provide me a sample of app used https://pub.dev/packages/google_ml_kit

**Comment by vudiuht** [comment]
@saikrishna321 could you help provide me a sample of app used https://pub.dev/packages/google_ml_kit

**Comment by saikrishna321** [comment]
@vudiuht Sorry the sample which we used is based in image_picker
