### ISSUE TITLE
Scroll Into View

### ISSUE THREAD

**Issue by thuonglai** [AppiumTestDistribution/appium-flutter-integration-driver#88]
Hi @saikrishna321 . Does Appium flutter integration driver have command ScrollIntoView as Appium flutter driver?

**Comment by saikrishna321** [comment]
Yes please check the docs

**Comment by thuonglai** [comment]
@saikrishna321 . In appium flutter driver, scroll into view has parameter alignment "scrollIntoView(item, alignment: alignment);".  So I can scroll element to center of listView. Function scrollTillVisible can not do it

**Comment by saikrishna321** [comment]
@thuonglai Can you please explain your use case?

**Comment by thuonglai** [comment]
@saikrishna321 . As the following picture, when i want choose CA state, i do scrollTillVisible. But it just stop in picture. I want it scroll to position of CT to choose it. Because this widget cann't click on item. 
![Screenshot_2024-08-19-21-05-21-134_com axlehire drive staging](https://github.com/user-attachments/assets/beb0d093-729c-4814-97b8-47c39bd9b1ef)

**Comment by saikrishna321** [comment]
@thuonglai does it even scroll in the pickerwheel?

**Comment by thuonglai** [comment]
@saikrishna321 . When i add option scrollView in Java, it still throw expection "org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: type 'Null' is not a subtype of type 'String' in type cast
" (Java-client version 9.3.0 + appium_flutter_server: 0.0.26)

**Comment by saikrishna321** [comment]
@thuonglai Can you share the code snippet please

**Comment by thuonglai** [comment]
@saikrishna321 . This is my code 
```
WebElement scrollable = androidDriver().findElement(FlutterBy.key(axlPickerItem));
        ScrollOptions scrollOptions = new ScrollOptions(FlutterBy.key(axlPickerItem + "_" + index), ScrollOptions.ScrollDirection.UP);
        scrollOptions.setMaxScrolls(50);
        scrollOptions.setScrollView(scrollable);
        WebElement element = FlutterCommands.scrollTillVisible(androidDriver(), scrollOptions);
        element.click();
```

**Comment by MummanaSubramanya** [comment]
I got the same issue and I think its a defect at line  https://github.com/appium/java-client/blob/b96c86803dedf639bc342b4b38d35e393de2ea2a/src/main/java/io/appium/java_client/flutter/commands/ScrollParameter.java#L59 . It needs to converted to parseFlutterLocator(scrollView).

here is the scroll snippet which worked for me 
`Map<String, Object> params= new HashMap<>(); 
params.put("finder", Map.of("using" ,"-flutter key" , "value" , "label_Category")); 
params.put("scrollView", Map.of("using" ,"-flutter type" , "value" , "CustomScrollView")); params.put("delta", 100); params.put("scrollDirection", "down"); params.put("maxScrolls", 50); params.put("settleBetweenScrollsTimeout", 20); params.put("dragDuration", 50); driver.executeFlutterCommand("scrollTillVisible", params);
`

**Comment by saikrishna321** [comment]
@MummanaSubramanya Thanks for a workaround. As you have spotted the issue, would you like to create a PR to java-client?

**Comment by rohitbhoite** [comment]
Is this issue resolved? I am also facing a similar issue. Actual requirement is to scroll the list within a bottomSheet but as it was not working I recreated a simple screen and tried but its not working for simple listview scenario as well. May be I am missing something

Flutter code:
```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:testint/detail_page.dart';
class ThirdPage extends StatefulWidget {
  const ThirdPage({super.key});

  @override
  State<ThirdPage> createState() => _ThirdPageState();
}

class _ThirdPageState extends State<ThirdPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(appBar:AppBar(title: Text("Third page"),),body:
    Container(
      child: Expanded(child: ListView.builder(
          key: Key("scrollList"),
          itemCount: 40,
          itemBuilder: (BuildContext context, int index) {
            return ListTile(
                key: Key("item:$index"),
                onTap: (){
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => const DetailPage(),
                      // Pass the arguments as part of the RouteSettings. The
                      // DetailScreen reads the arguments from these settings.
                      settings: RouteSettings(
                        arguments: index,
                      ),
                    ),
                  );


                },
                leading: const Icon(Icons.list),
                trailing: const Text(
                  "GFG",
                  style: TextStyle(color: Colors.green, fontSize: 15),
                ),
                title: Text("List item $index"));
          }),),
    ),);
  }
}

```



Appium test code
 ```
 await browser.flutterScrollTillVisible({

          finder: await browser.flutterByValueKey$('item:40'),

          scrollDirection:'up',

     

          scrollView: await browser.flutterByValueKey$('scrollList'),

       });

        const elementButton = await browser

        .flutterByValueKey$('item:40');

        await elementButton.click();   
```




Configuration:

```
capabilities: [

        {

            platformName: 'Android',

            'appium:deviceName': process.env.DEVICE_NAME || 'Google Pixel.*',

            'appium:automationName': 'FlutterIntegration',

            'appium:app': 'storage:filename=app-debug.apk',

            'appium:newCommandTimeout': 240,

            'sauce:options': {

                name: "appium test",

                appiumVersion: "latest",

                sauceLabsImageInjectionEnabled: true

            },

            'appium:autoGrantPermissions': true,

        }

    ],

```

**Comment by saikrishna321** [comment]
Yes this issue is fixed and is in java-client main. 

Please use the latest commit from java-client

**Comment by rohitbhoite** [comment]
Isn't it fixed for typescript client?

**Comment by saikrishna321** [comment]
Can you try 


await browser.flutterScrollTillVisible({

         finder: await browser.flutterByValueKey$('item:40'),

         scrollDirection:'up',

    

         scrollView: await browser.flutterByValueKey('scrollList'),

      });

**Comment by rohitbhoite** [comment]
Yes I am using the same code. Please refer the code I added above.
Using flutterByValueKey$ instead of flutterByValueKey for scrollview param

**Comment by saikrishna321** [comment]
`Using flutterByValueKey$ instead of flutterByValueKey for scrollview param` This didn't work?

**Comment by rohitbhoite** [comment]
On portal I can see the below error message/
"{\"value\":{\"error\":\"unknown error\",\"message\":\"An unknown server-side error occurred while processing the command. Original error: Exception: Element with locator widget with key [<'item:40'>] (considering only hit-testable ones) is not present in DOM with 5 seconds\",\"stacktrace\":\"UnknownError: An unknown server-side error occurred while processing the command. Original error: Exception: Element with locator widget with key [<'item:40'>] (considering only hit-testable ones) is not present in DOM with 5 seconds\\n    at errorFromW3CJsonCode (/root/appium/appium2-20240 [truncated]"

**Comment by sudharsan-selvaraj** [comment]
Both `finder` and `scrollView` should be a locator. Can you try the below code?

```
await browser.flutterScrollTillVisible({
     finder: await browser.flutterByValueKey('item:40'),
     scrollDirection:'up',
     scrollView: await browser.flutterByValueKey('scrollList'),
  });
```

**Comment by rohitbhoite** [comment]
<img width="947" alt="image" src="https://github.com/user-attachments/assets/4c0b770a-2659-4f34-8542-31f544546adc">

Vscode gives an error if I use `await browser.flutterByValueKey`

**Comment by saikrishna321** [comment]
@rohitbhoite This is typings issue. Can you do ts-ignore and try

**Comment by rohitbhoite** [comment]
Thanks it worked
