### ISSUE TITLE
Getting pumpAndSettle Timeout Error while using scrollTillVisible

### ISSUE THREAD

**Issue by MummanaSubramanya** [AppiumTestDistribution/appium-flutter-integration-driver#89]
Hey,

First of all thank you making this driver available.

Now coming to the issue, I am getting error as pumpAndSettle Timeout error when using scrollTillVisible. Below is the code snippet i used 

```
Map<String, Object> params= new HashMap<>(); 

params.put("finder", Map.of("using" ,"-flutter key" , "value" , "label_Category"));

 params.put("scrollView", Map.of("using" ,"-flutter type" , "value" , "CustomScrollView")); 

params.put("delta", 100);

 params.put("scrollDirection", "down"); 

params.put("maxScrolls", 50); 

params.put("settleBetweenScrollsTimeout", 20); 

params.put("dragDuration", 50); 

driver.executeFlutterCommand("scrollTillVisible", params);

```

After debugging, I identified that the issue is being caused by the following line: https://github.com/AppiumTestDistribution/appium-flutter-server/blob/e2cf4bc2378146ef2caf663af2ffb98708ffd763/server/lib/src/utils/element_helper.dart#L540.

I commented out this line, built the server locally, and the issue was resolved—I no longer receive the exception. My question is: is this code necessary? If so, can we make chnages to pass pumpAndSettle  arugument as optional ?

**Comment by saikrishna321** [comment]
@MummanaSubramanya Make sense! For now I have added a fix to use pumpTryAndSettle that should fix this problem. 

We should allow users to choose pumpTryAndSettle, pump, pumpSettle or ignore. Will add a settings API for this.

**Comment by MummanaSubramanya** [comment]
resolved
