### ISSUE TITLE
[ASK] Is there any way to declare element based on descendant, ancestor, sibling, etc ?

### ISSUE THREAD

**Issue by Tegardoa** [AppiumTestDistribution/appium-flutter-integration-driver#93]
Hello,

I want to migrate from appium-flutter-driver to appium-flutter-integration-driver.
But it seems on documentation [Get-Started](https://github.com/AppiumTestDistribution/appium-flutter-integration-driver/wiki/Get-Started), there is no example related to finding element using descendant, ancestor, sibling, etc.

Normally in appium-flutter-driver, I can use ancestor like this 
`finder.ancestor({ of: finder.byText('Company Name'), matching: finder.byType('CompanyListCard') })`
and I can use descendant like this
`finder.descendant({ of: finder.byType('SizedBox'), matching: finder.byText('Button Name') })`

Is it possible to do that in this driver ? If it's possible, can you give example for this case ?

**Comment by saikrishna321** [comment]
@Tegardoa Yes we support. We follow top bottom approach. 

```
  const element = await browser
         .flutterByValueKey$('double_tap_button')
         .flutterByText$('Double Tap');
      expect(await element.getText()).toEqual('Double Tap');
```

**Comment by Tegardoa** [comment]
@saikrishna321 i see, never heard about that before, because I usually use xpath to declare child/parent. How about bottom top approach ? using child as reference to get the parent, is it possible too ? or is there other way in this driver ?

**Comment by saikrishna321** [comment]
@Tegardoa Haven't tested it.. Should work. Give it a try.

**Comment by Tegardoa** [comment]
thanks for the solution cheers
