### ISSUE TITLE
Unable to run appium flutter tests locally

### ISSUE THREAD

**Issue by rohitbhoite** [AppiumTestDistribution/appium-flutter-integration-driver#94]
I am trying to run Flutter appium tests locally but I am getting TypeError: browser.flutterByValueKey$ is not a function error. What could be the cause of this issue.

appium-flutter-integration-driver is installled.App is created as per the instructions and  verified that appium server is running properly.

```
// @ts-ignore
import { browser, expect } from '@wdio/globals';
import "jest"

// Importing FlutterIntergrationDriverService from 'wdio-flutter-by-service'
// to extend browser capabilities with Flutter-specific methods.
// @ts-ignore
import FlutterIntergrationDriverService from 'wdio-flutter-by-service';

describe('1st AppiumFlutterIntegrationDriver test using appium latest', () => {
  it('Flutter counter demo app', async () => {
    const incrementButton = await browser
         .flutterByValueKey$('incrementButton');
  });
});
```

<img width="851" alt="image" src="https://github.com/user-attachments/assets/bfc05614-3f99-4c2c-a677-abaca60caa36">

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/e067adb4-951b-4427-965c-32f0df51f8f8">

**Comment by saikrishna321** [comment]
@rohitbhoite Please refer the sample here - https://github.com/AppiumTestDistribution/appium-flutter-integration-driver/blob/main/test/specs/test.e2e.js

**Comment by rohitbhoite** [comment]
Actually I am able to run these scripts on saucelab cloud but why its giving error if i try to run these tests locally.
`TypeError: browser.flutterByValueKey$ is not a function`

**Comment by rohitbhoite** [comment]
Any idea what could be the cause of this issue while running the tests locally?

**Comment by sudharsan-selvaraj** [comment]
It looks like there might be a problem with how you're importing the Flutter service. Instead of importing it directly into the spec file, you should add it to the WebdriverIO configuration file.

```
{
 "services" : ["flutter-by"]
}
```

**Comment by bhadmustests** [comment]
I have done this but I still got this error;

`TypeError: browser.flutterByText$ is not a function
    at ScreenPage.clickingGetStartedButton (/Users/sanguine/Tutorial/projects/complete_al_mathurat_app/auto/test/pageobjects/screens.page.js:15:38)
    at Context.<anonymous> (/Users/sanguine/Tutorial/projects/complete_al_mathurat_app/auto/test/specs/test.e2e.js:6:26)`

> It looks like there might be a problem with how you're importing the Flutter service. Instead of importing it directly into the spec file, you should add it to the WebdriverIO configuration file.
> 
> ```
> {
>  "services" : ["flutter-by"]
> }
> ```
