### ISSUE TITLE
FlutterServer not reachable on port 10001, Retrying..

### ISSUE THREAD

**Issue by pseudox07** [AppiumTestDistribution/appium-flutter-integration-driver#97]
Currently in my local setup, I kept getting error "FlutterServer not reachable on port 10000".
Already setup as per https://github.com/AppiumTestDistribution/appium-flutter-integration-driver : 

- Flutter Integration Driver
- set dependencies on app side
- create integration_test folder and setup appium.dart
- build the apk from flutter build apk for android

Below are my logs snippet. for full log please find attached.
[logs.txt](https://github.com/user-attachments/files/17072800/logs.txt)

Already did my research, havent found any similar issue.
I configured with WDIO framework and Appium-Python-Client, still having the same issue.

`
2024-09-20 08:20:02:329 [2bbd8034][AndroidUiautomator2Driver@098e] Got response with status 200: {"sessionId":"c915bfb8-39f5-4e31-b32a-e9e43d84d2dd","value":"PORTRAIT"}
2024-09-20 08:20:02:332 [2bbd8034][ADB] Forwarding system: 10001 to device: 9000
2024-09-20 08:20:02:332 [2bbd8034][ADB] Running 'C:\Users\user\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward tcp:10001 tcp:9000'
2024-09-20 08:20:02:367 [2bbd8034][38;5;-2m[AppiumFlutterDriver@86e1] Checking if flutter server is running on port 9000
2024-09-20 08:20:02:369 [2bbd8034][WD Proxy] Matched '/status' to command name 'getStatus'
2024-09-20 08:20:02:370 [2bbd8034][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10001/status] with no body
2024-09-20 08:20:02:419 [2bbd8034][WD Proxy] socket hang up
2024-09-20 08:20:02:420 [2bbd8034][38;5;-2m[AppiumFlutterDriver@86e1] FlutterServer not reachable on port 10001, Retrying..
2024-09-20 08:20:02:572 [2bbd8034][WD Proxy] Matched '/status' to command name 'getStatus'
2024-09-20 08:20:02:572 [2bbd8034][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10001/status] with no body`

Let me know if need more info, appreciate guidance and help on this.

**Comment by saikrishna321** [comment]
@pseudox07 

Can you please verify if the application is build with the server. 

1. Run adb command `adb logcat | grep flutter` to check if the Flutter app is running.
2. Open the application in the device or emulator manually.
3. Verify the logs in the console.

```
06-17 17:02:13.246 32697 32743 I flutter : The Dart VM service is listening on http://127.0.0.1:33339/E2REX61NaiI=/
06-17 17:02:13.584 32697 32735 I flutter : 00:00 +0: appium flutter server
06-17 17:02:14.814 32697 32735 I flutter : shelfRun HTTP service running on port 9000
06-17 17:02:14.814 32697 32735 I flutter : [APPIUM FLUTTER]  Appium flutter server is listening on port 9000
06-17 17:02:14.866 32697 32735 I flutter : [APPIUM FLUTTER]  New Request [GET] http://127.0.0.1:10000/status
06-17 17:02:14.869 32697 32735 I flutter : [APPIUM FLUTTER]  response {message: Flutter driver is ready to accept new connections, appInfo: {appName: appium_testing_app, buildNumber: 1, packageName: com.example.appium_testing_app, version: 1.0.0, buildSignature: F2C7CEC8F907AB830B7802C2178515D1FD4BEBA154E981FB61FFC8EC9A8F8195}}
```

**Comment by pseudox07** [comment]
Seems like the server is installed in the app

```	 09-20 13:19:39.887  5068  5200 I flutter : The Dart VM service is listening on http://127.0.0.1:36067/QQH-UNssswY=/
	 09-20 13:19:40.766  5068  5190 I flutter : 00:00 +0: appium flutter server
	 09-20 13:19:41.953  5068  5190 I flutter : shelfRun HTTP service running on port 9000
	 09-20 13:19:41.956  5068  5190 I flutter : [APPIUM FLUTTER]  Appium flutter server is listening on port 9000
	 09-20 13:22:29.907  5704  5818 I flutter : The Dart VM service is listening on http://127.0.0.1:36283/g6bnlKjakno=/
	 09-20 13:22:30.292  5704  5810 I flutter : 00:00 +0: appium flutter server
	 09-20 13:22:31.258  5704  5810 I flutter : shelfRun HTTP service running on port 9000
	 09-20 13:22:31.259  5704  5810 I flutter : [APPIUM FLUTTER]  Appium flutter server is listening on port 9000
	 09-20 13:23:09.245  5704  5810 I flutter : TEST
	 09-20 13:23:16.436  5704  5810 I flutter : Firebase User ID set to: 23d7f6d0-359b-4db5-bf43-95a967038597
	 09-20 13:23:17.545  5704  5810 I flutter : Null check operator used on a null value
	 09-20 13:23:17.545  5704  5810 I flutter : #0      State.setState (package:flutter/src/widgets/framework.dart:1223)
	 09-20 13:23:17.545  5704  5810 I flutter : #1      _MXPhoneNumberTextFieldState._validateField (package:mx_widgets/src/widgets/form_fields/mx_phone_number_text_field.dart:300)
	 09-20 13:23:17.545  5704  5810 I flutter : <asynchronous suspension>
	 09-20 13:23:17.545  5704  5810 I flutter : 00:47 +0: appium flutter server [E]
	 09-20 13:23:17.545  5704  5810 I flutter :   Test failed. See exception logs above.
	 09-20 13:23:17.545  5704  5810 I flutter :   The test description was: appium flutter server
	 09-20 13:23:17.545  5704  5810 I flutter :   
	 09-20 13:23:17.546  5704  5810 I flutter : 00:47 +0 -1: (tearDownAll)
	 09-20 13:23:17.548  5704  5810 I flutter : 00:47 +0 -1: appium flutter server
	 09-20 13:23:17.548  5704  5810 I flutter : Null check operator used on a null value
	 09-20 13:23:17.548  5704  5810 I flutter : #0      State.setState (package:flutter/src/widgets/framework.dart:1223)
	 09-20 13:23:17.548  5704  5810 I flutter : #1      _MXPhoneNumberTextFieldState._validateField (package:mx_widgets/src/widgets/form_fields/mx_phone_number_text_field.dart:300)
	 09-20 13:23:17.548  5704  5810 I flutter : <asynchronous suspension>
	 09-20 13:23:17.560  5704  5810 I flutter : Null check operator used on a null value
	 09-20 13:23:17.561  5704  5810 I flutter : #0      State.setState (package:flutter/src/widgets/framework.dart:1223)
	 09-20 13:23:17.561  5704  5810 I flutter : #1      _MXPhoneNumberTextFieldState._validateField (package:mx_widgets/src/widgets/form_fields/mx_phone_number_text_field.dart:300)
	 09-20 13:23:17.561  5704  5810 I flutter : <asynchronous suspension>
	 09-20 13:23:17.720  5704  5810 I flutter : 00:47 +1 -1: Some tests failed.

```
but seems no further [APPIUM FLUTTER] log after that

**Comment by saikrishna321** [comment]
There is a crash! U need to fix them

**Comment by pseudox07** [comment]
@saikrishna321 ,
The crash is already fix after I upgraded appium_flutter_server=0.0.14 to 0.0.27 and upgrade my flutter sdk, but I got errors

-  " [APPIUM FLUTTER]  Instance of 'ErrorModel'" in adb logcat 
- appium is showing this 

> "[WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up](webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Exception: Element with locator widget with key [<'btn_login'>] (considering only hit-testable ones) is not present in DOM with 5 seconds)"

Is this something related to animations in the app?
I tried suggestion to use waitForDisplayed and waitForEnabled to wait for the animations to complete. But still getting the above error.

> 	 09-22 03:46:57.589 18738 18834 I flutter : [APPIUM FLUTTER]  Appium flutter server is listening on port 9000
	 09-22 03:46:58.090 18738 18834 I flutter : [APPIUM FLUTTER]  New Request [GET] http://127.0.0.1:10003/status
	 09-22 03:46:58.090 18738 18834 I flutter : [APPIUM FLUTTER]  response {message: Flutter driver is ready to accept new connections, appInfo: {appName: exmapleapp UAT, buildNumber: 1, packageName: com.company.exmapleapp.uat, version: 3.2.0, buildSignature: ##########################################}, serverVersion: 0.0.27}
	 09-22 03:46:58.090 18738 18834 I flutter : [APPIUM FLUTTER]  {message: Flutter driver is ready to accept new connections, appInfo: {appName: exmapleapp UAT, buildNumber: 1, packageName: com.company.exmapleapp.uat, version: 3.2.0, buildSignature: ###################################}, serverVersion: 0.0.27}
	 09-22 03:46:58.155 18738 18834 I flutter : [APPIUM FLUTTER]  New Request [POST] http://127.0.0.1:10003/session
	 09-22 03:46:58.155 18738 18834 I flutter : [APPIUM FLUTTER]  response {}
	 09-22 03:46:58.155 18738 18834 I flutter : [APPIUM FLUTTER]  {}
	 09-22 03:46:58.594 18738 18834 I flutter : [APPIUM FLUTTER]  New Request [POST] http://127.0.0.1:10003/session/c588f709-dec9-4e81-a83b-525f7e80cbd8/element
	 09-22 03:46:58.594 18738 18834 I flutter : [APPIUM FLUTTER]  "method: -flutter key, selector: btn_login
	 09-22 03:47:03.766 18738 18834 I flutter : [APPIUM FLUTTER]  #0      ElementHelper.waitFor (package:appium_flutter_server/src/utils/element_helper.dart:448)
	 09-22 03:47:03.766 18738 18834 I flutter : [APPIUM FLUTTER]  Instance of 'ErrorModel'
	 09-22 03:47:03.997 18738 18834 I flutter : [APPIUM FLUTTER]  New Request [POST] http://127.0.0.1:10003/session/c588f709-dec9-4e81-a83b-525f7e80cbd8/element
	 09-22 03:47:03.997 18738 18834 I flutter : [APPIUM FLUTTER]  "method: -flutter key, selector: btn_login
	 09-22 03:47:09.040 18738 18834 I flutter : [APPIUM FLUTTER]  #0      ElementHelper.waitFor (package:appium_flutter_server/src/utils/element_helper.dart:448)
	 09-22 03:47:09.040 18738 18834 I flutter : [APPIUM FLUTTER]  Instance of 'ErrorModel'
	 
	 
Below are my codes
`async clickLoginButton() {
    const login = await browser.flutterByValueKey$("btn_login");
    await login.waitForDisplayed({ timeout: 10000 });
    await login.waitForEnabled({ timeout: 10000 });
    await login.click();
  }`

Been looking for workaround on this in the net.
Any suggestions/input you have that can help me to expedite this further?

**Comment by saikrishna321** [comment]
@pseudox07 when finding element we by default waitFor the element to be hitable. Thats the reason it's not working. 

We will make it configurable

**Comment by pseudox07** [comment]
I am still getting same error but with 30 seconds timeout instead.

> [AppiumFlutterDriver@d90f] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Exception: Element with locator widget with key [<'btn_login'>] (considering only hit-testable ones) is not present in DOM with 30 seconds

below are my caps.
```
{
        // The defaults you need to have in your config
        platformName: 'Android',
        maxInstances: 5,
        'appium:deviceName': 'Pixel_7a_API_30',
        'appium:platformVersion': '11.0',
        'appium:orientation': 'PORTRAIT',
        'appium:automationName': 'FlutterIntegration',
        "appium:autoGrantPermissions": true,
        'appium:app': "app/app-androiduat-profile.apk",
        'appium:appPackage': 'com.company.app.uat',
        'appium:appWaitActivity': 'com.company.app.MainActivity',
        'appium:noReset': false,
        'appium:newCommandTimeout': 240,
        'appium:flutterElementWaitTimeout': 30000
    },
```
I m wondering if the element is traceable from app or not, currently the keys is traceable from widget inspector.
I tried to execute 'flutter: getRenderTree', but seems its not supported

>  Unsupported execute method 'flutter: getRenderTree'. Available methods are: flutter: doubleClick, flutter: waitForVisible, flutter: waitForAbsent, flutter: scrollTillVisible, flutter: longPress, flutter: dragAndDrop, flutter: launchApp, flutter: injectImage, flutter: activateInjectedImage

**Comment by saikrishna321** [comment]
@pseudox07 can you share the dom when you inspect through flutter dev tools?

**Comment by pseudox07** [comment]
Yeah, its visible in the app. Can see the Widget tree below for the app hierarchy.
![image](https://github.com/user-attachments/assets/41bb0bbf-5cce-49cd-95e4-65dfe123cdb4)

**Comment by saikrishna321** [comment]
@pseudox07 Is it possible to get a sample app code to render this view to test ?

**Comment by pseudox07** [comment]
I can give the code snapshots, 
![image](https://github.com/user-attachments/assets/889c5d59-84d4-4c95-b1d4-dbb4b89ff628)
![image](https://github.com/user-attachments/assets/1e800e1b-9354-4c5d-8ba2-1df077bbea19)
The developers only implemented keys in the widget, but not the semantics label. Aside the keys, is there anything that's need setup?

**Comment by saikrishna321** [comment]
@pseudox07 Is MXButton magentic_button ? flutter pub add magnetic_button https://pub.dev/packages/magnetic_button

**Comment by pseudox07** [comment]
the button is not magnetic button, its a internal package that the devs used. For your suggestion on the Valuekey, Im still getting the 

> Exception: Element with locator widget with key [<'btn_login'>] (considering only hit-testable ones) is not present in DOM with 30 seconds

**Comment by saikrishna321** [comment]
@pseudox07 Without a sample application it's hard to debug and fix the issue. If its an internal package not sure how we can help. 

We look if the element is visible on the screen - https://github.com/AppiumTestDistribution/appium-flutter-server/blob/main/server/lib/src/utils/element_helper.dart#L44

Please try to provide the full code snippet and the dependency we can debug the issue.

**Comment by pseudox07** [comment]
Im able to resolve this issue after i change from browser to driver. 

`await driver.flutterFindByValueKeys(")`

i was following from this[ tuto ](https://medium.com/@ambysan/flutter-app-testing-with-appium-flutter-integration-driver-and-webdriverio-all-you-need-to-know-1183831cfeee).  I realise WDIO only enable browser for browser testings.

not an issue from appium-flutter-intgeration-driver.
